"""
RetrievalService — the full retrieval pipeline.

Pipeline (executed per user query):
  1. QueryRewriter       – expand one query into N diverse sub-queries
  2. Semantic Search     – BGE dense vectors via Pinecone (per sub-query)
  3. BM25 Search         – sparse keyword search over all user chunks
  4. Reciprocal Rank Fusion (RRF) – merge ranked lists without score normalisation
  5. CrossEncoder Reranker – BGE reranker scores every candidate against the
                             ORIGINAL query for final ordering
  6. ContextCompressor   – trim each passage to the most relevant sentences,
                           reducing prompt tokens while preserving meaning

All stateful objects (embedder, reranker, BM25 cache) are module-level
singletons so they are loaded once and reused across requests.
"""

import logging
import re
from typing import Any

from cachetools import TTLCache, cached
import google.generativeai as genai

from backend.config.settings import settings
from backend.prompts.llm_prompts import QUERY_REWRITE_PROMPT
from backend.utils.vector_store import get_pinecone_index

logger = logging.getLogger(__name__)

# Configure Gemini once — no heavy model weights downloaded
genai.configure(api_key=settings.GEMINI_API_KEY)

def get_query_embedding(text: str) -> list[float]:
    """768-dim query embedding via Gemini text-embedding-004."""
    result = genai.embed_content(
        model="models/text-embedding-004",
        content=text,
        task_type="retrieval_query",
    )
    return result["embedding"]


# BM25 index is rebuilt per user and cached for 5 minutes (TTL=300 s).
# maxsize=50 covers 50 distinct users concurrently without unbounded growth.
bm25_cache: TTLCache = TTLCache(maxsize=50, ttl=300)

# ---------------------------------------------------------------------------
# Tuning knobs (centralised so they're easy to experiment with)
# ---------------------------------------------------------------------------
NUM_REWRITE_QUERIES   = 3    # additional queries generated by the LLM
SEMANTIC_TOP_K        = 15   # results per sub-query from Pinecone
BM25_TOP_K            = 15   # results from BM25 per query
RRF_K                 = 60   # RRF constant (higher = more forgiving rank penalty)
RERANK_TOP_N          = 10   # candidates passed to the CrossEncoder
FINAL_TOP_N           = 5    # chunks returned to ChatService
COMPRESS_MAX_SENTENCES = 4   # sentences kept per chunk after compression


# ===========================================================================
# 1.  Query Rewriter
# ===========================================================================
class QueryRewriter:
    """
    Generates NUM_REWRITE_QUERIES diverse reformulations of the user's question.

    This improves recall by covering synonyms, different phrasings, and
    adjacent topics that a single query might miss.

    Falls back to [original_question] if the LLM call fails, so retrieval
    always continues.
    """

    @staticmethod
    def rewrite(question: str) -> list[str]:
        # Import here to avoid circular imports at module load time
        from backend.services.llm import LLMService

        prompt = QUERY_REWRITE_PROMPT.format(
            n=NUM_REWRITE_QUERIES, question=question
        )
        raw = LLMService.call(prompt, max_tokens=256, temperature=0.4)
        if not raw:
            logger.warning("QueryRewriter received empty response; using original.")
            return [question]

        # Parse newline-separated list; strip bullets/numbers if LLM added them
        queries = []
        for line in raw.strip().splitlines():
            clean = re.sub(r"^[\d\.\-\*\s]+", "", line).strip()
            if clean:
                queries.append(clean)

        # Always include the original as the first query
        all_queries = [question] + queries
        logger.debug("Rewritten queries: %s", all_queries)
        return all_queries


# ===========================================================================
# 2.  BM25 Index (cached per user)
# ===========================================================================
class BM25Index:
    """
    Builds and caches a BM25Okapi index over all chunks owned by *user_id*.

    Importing rank_bm25 here (not at module top) keeps the dependency
    optional — if rank_bm25 is not installed, BM25 gracefully degrades.
    """

    @staticmethod
    @cached(bm25_cache)
    def build(user_id: int):
        """Returns (bm25, docs, metadatas, ids) or (None, [], [], [])."""
        try:
            from rank_bm25 import BM25Okapi
        except ImportError:
            logger.warning("rank_bm25 not installed; BM25 leg disabled.")
            return None, [], [], []

        index = get_pinecone_index()
        try:
            results = index.query(
                vector=[0.0] * 768,
                top_k=10000,
                filter={"user_id": str(user_id)},
                include_metadata=True,
            )
            matches = results.get("matches", [])
            docs      = [m["metadata"].get("text", "")     for m in matches]
            metadatas = [m["metadata"]                      for m in matches]
            ids       = [m["id"]                            for m in matches]
            tokenised = [doc.lower().split() for doc in docs]
            bm25      = BM25Okapi(tokenised)
            return bm25, docs, metadatas, ids
        except Exception as exc:
            logger.error("BM25Index.build failed: %s", exc)
            return None, [], [], []

    @staticmethod
    def clear():
        bm25_cache.clear()


# ===========================================================================
# 3.  Reciprocal Rank Fusion
# ===========================================================================
class RRFFusion:
    """
    Merges multiple ranked result lists using Reciprocal Rank Fusion.

    RRF score = Σ  1 / (k + rank_i)

    RRF is robust to score-scale differences between BM25 and cosine
    similarity — no normalisation required.
    """

    @staticmethod
    def fuse(
        ranked_lists: list[list[dict[str, Any]]],
        k: int = RRF_K,
    ) -> list[dict[str, Any]]:
        scores: dict[str, float]    = {}
        store:  dict[str, dict]     = {}

        for ranked in ranked_lists:
            for rank, item in enumerate(ranked, start=1):
                chunk_id = item["metadata"].get("chunk_id", "")
                if not chunk_id:
                    continue
                scores[chunk_id] = scores.get(chunk_id, 0.0) + 1.0 / (k + rank)
                store[chunk_id]  = item

        sorted_ids = sorted(scores, key=lambda cid: scores[cid], reverse=True)
        return [store[cid] for cid in sorted_ids]


# ===========================================================================
# 4.  Context Compressor
# ===========================================================================
class ContextCompressor:
    """
    Extracts only the sentences in a chunk that are most relevant to the query.

    Strategy: score each sentence by token-overlap with the query (fast, no
    extra model needed).  Keep the top COMPRESS_MAX_SENTENCES sentences in
    their original order so the passage remains coherent.

    If a chunk is short enough to fit entirely, it is returned as-is.
    """

    @staticmethod
    def compress(text: str, query: str, max_sentences: int = COMPRESS_MAX_SENTENCES) -> str:
        # Split on sentence boundaries
        sentences = re.split(r"(?<=[.!?])\s+", text.strip())
        if len(sentences) <= max_sentences:
            return text

        query_tokens = set(query.lower().split())

        def relevance(sentence: str) -> float:
            tokens = set(sentence.lower().split())
            overlap = len(tokens & query_tokens)
            # Prefer medium-length sentences over very short or very long ones
            length_bonus = min(len(tokens), 20) / 20.0
            return overlap + 0.1 * length_bonus

        scored = sorted(
            enumerate(sentences),
            key=lambda pair: relevance(pair[1]),
            reverse=True,
        )
        # Take the top-N by index to preserve original reading order
        kept_indices = sorted(idx for idx, _ in scored[:max_sentences])
        return " ".join(sentences[i] for i in kept_indices)


# ===========================================================================
# 5.  RetrievalService — public API consumed by ChatService
# ===========================================================================
class RetrievalService:
    """
    Public façade for the full retrieval pipeline.

    Only hybrid_search() and clear_bm25_cache() are called from outside.
    """

    # ── BM25 cache management (called by EmbeddingsService after ingestion) ──
    @staticmethod
    def clear_bm25_cache() -> None:
        BM25Index.clear()

    # ── Main entry-point ─────────────────────────────────────────────────────
    @staticmethod
    def hybrid_search(
        query: str,
        user_id: int,
        top_k: int = SEMANTIC_TOP_K,
    ) -> list[dict[str, Any]]:
        """
        Execute the full retrieval pipeline and return up to FINAL_TOP_N chunks.

        Each returned item is a dict:
          {
            "document":    str   — child chunk text (for embedding / BM25)
            "parent_text": str   — full parent passage (used by ContextCompressor)
            "metadata":    dict  — source_file, page_number, section_header, …
            "score":       float — CrossEncoder reranker score
          }
        """
        index = get_pinecone_index()

        # ── Step 1: Query rewriting ───────────────────────────────────────
        all_queries = QueryRewriter.rewrite(query)

        # ── Step 2: Semantic search — one Pinecone call per sub-query ────
        all_semantic_lists: list[list[dict]] = []
        for sub_query in all_queries:
            try:
                q_emb = get_query_embedding(sub_query)
                res   = index.query(
                    vector=q_emb,
                    top_k=top_k,
                    filter={"user_id": str(user_id)},
                    include_metadata=True,
                )
                ranked = [
                    {
                        "document":    m["metadata"].get("text",        ""),
                        "parent_text": m["metadata"].get("parent_text", ""),
                        "metadata":    m["metadata"],
                    }
                    for m in res.get("matches", [])
                ]
                all_semantic_lists.append(ranked)
            except Exception as exc:
                logger.error("Semantic search failed for query '%s': %s", sub_query, exc)

        # ── Step 3: BM25 search (original query only for speed) ───────────
        bm25, all_docs, all_metadatas, _ = BM25Index.build(user_id)
        bm25_ranked: list[dict] = []
        if bm25 and all_docs:
            tokenised_q = query.lower().split()
            doc_scores  = bm25.get_scores(tokenised_q)
            top_indices = sorted(
                range(len(doc_scores)),
                key=lambda i: doc_scores[i],
                reverse=True,
            )[:BM25_TOP_K]
            bm25_ranked = [
                {
                    "document":    all_docs[i],
                    "parent_text": all_metadatas[i].get("parent_text", ""),
                    "metadata":    all_metadatas[i],
                }
                for i in top_indices
            ]

        # ── Step 4: Reciprocal Rank Fusion ────────────────────────────────
        all_ranked_lists = all_semantic_lists + ([bm25_ranked] if bm25_ranked else [])
        if not all_ranked_lists:
            logger.warning("No results from any retrieval leg for user %d.", user_id)
            return []

        fused = RRFFusion.fuse(all_ranked_lists)

        top_chunks = fused[:FINAL_TOP_N]

        # Assign RRF scores so downstream code still has a "score" field
        for i, item in enumerate(top_chunks):
            item.setdefault("score", 1.0 / (i + 1))

        # ── Step 6: Context compression ───────────────────────────────────
        for item in top_chunks:
            # Use the parent passage as the base text if available (richer context)
            base_text = item.get("parent_text") or item["document"]
            item["compressed_text"] = ContextCompressor.compress(base_text, query)

        logger.info(
            "Retrieval complete: %d queries → %d fused → %d reranked → %d returned",
            len(all_queries), len(fused), len(candidates), len(top_chunks),
        )
        return top_chunks
