/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-variant": "#353628",
        "error-container": "#93000a",
        "tertiary-fixed": "#e5e2e1",
        "surface-dim": "#131409",
        "primary": "#fbf7e4",
        "inverse-primary": "#605f50",
        "surface-tint": "#cac7b5",
        "surface-container-low": "#1b1c10",
        "primary-fixed": "#e6e3d0",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-high": "#2a2b1e",
        "on-secondary-container": "#bab8b7",
        "tertiary": "#f9f6f6",
        "surface-container-highest": "#353628",
        "on-tertiary": "#303030",
        "on-surface": "#e5e3cf",
        "background": "#000000",
        "on-primary-container": "#616051",
        "on-secondary": "#313030",
        "primary-fixed-dim": "#cac7b5",
        "primary-container": "#dedbc8",
        "on-primary-fixed-variant": "#484739",
        "surface": "#131409",
        "on-surface-variant": "#c9c6bc",
        "on-primary": "#323124",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e3cf",
        "on-primary-fixed": "#1c1c10",
        "on-error": "#690005",
        "inverse-on-surface": "#303124",
        "on-tertiary-container": "#605f5f",
        "error": "#ffb4ab",
        "surface-bright": "#393a2c",
        "on-tertiary-fixed": "#1b1c1c",
        "secondary": "#c8c6c5",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-lowest": "#0e0f05",
        "inverse-surface": "#e5e3cf",
        "outline-variant": "#48473f",
        "tertiary-container": "#dcdad9",
        "outline": "#939187",
        "on-tertiary-fixed-variant": "#474746",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-container": "#4a4949",
        "surface-container": "#1f2014"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "2xl": "1.5rem"
      },
      "spacing": {
        "stack-lg": "4rem",
        "stack-sm": "0.5rem",
        "container-max": "1440px",
        "hero-inset": "4rem",
        "stack-md": "1.5rem",
        "section-padding": "8rem",
        "gutter": "2rem"
      },
      "fontFamily": {
        "headline-md": ["Almarai"],
        "accent-italic": ["Instrument Serif"],
        "headline-lg": ["Almarai"],
        "body-md": ["Almarai"],
        "display-lg-mobile": ["Almarai"],
        "body-lg": ["Almarai"],
        "label-sm": ["Almarai"],
        "display-lg": ["Almarai"]
      },
      "fontSize": {
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "400"}],
        "accent-italic": ["1.1em", {"fontWeight": "400"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg-mobile": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-lg": ["20px", {"lineHeight": "1.6", "fontWeight": "300"}],
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "display-lg": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
